### ISSUE TITLE
Partitioning and resizing

### ISSUE THREAD

**Issue by ghost** [mrfixit2001/debian_builds#1]
Expanding the free space into a 3rd partition mapped to /home severely limits what can be added onto the system later. I started porting retropie to the rockpro64 and ran out of space for the libraries and headers before I was half way through, but had 10 gb available in my home directory. I've been working around it by using my linux PC and removing partbootscript.sh and its associated systemd service and replacing extlinux.conf with the one created after the resize occurs.

**Comment by mrfixit2001** [comment]
First off, thanks for bringing this up! 
Let me start by saying in my next release I will make sure the system partition is expanded to about 5 gigs.

The purpose of keeping the home files on a separate partition than the system was to keep that system partition at a minimal size to slightly improve file IO and put the files that change most often on their own partition. 

The good news is that I'm almost done with a retropie port for the rockpro and rock64, and will provide a fully built image complete with kodi leia when I'm done with it. 

I'm surprised you ran out of space on the system partition, honestly, because I was able to fully port retropie without kodi on the current partition size just fine. But once I started adding kodi dependencies, it filled up quick.

In any event, you can workaround this issue using the parted utility by doing the following:
 - Backup any custom data you've added (if any) on your /home partition
 - Unmount the /home mount point
 - Remove the 3rd partition that was auto-created for home
 - Resize the second partition to the desired new size (I have found 5gb was plenty for me)
 - Resize the filesystem after resizing the partition (resize2fs /dev/<partition here>)
 - Reboot - this will re-create the third partition
 - Restore any custom data back to the /home partition

**Comment by mrfixit2001** [comment]
I have enhanced the capability of the bootpartscript in the new release to allow for a user to change the default to use only 2 partitions and expand the system partition to the full disk. Read the readme for  instructions, and please back-up your /home folder first!
